// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDIy_QqInrk2yp3E3Jlua7e9icTBtWuzD8',
    appId: '1:885122827085:web:94144696560090429e6d04',
    messagingSenderId: '885122827085',
    projectId: 'cardioresp-ai',
    authDomain: 'cardioresp-ai.firebaseapp.com',
    storageBucket: 'cardioresp-ai.appspot.com',
    measurementId: 'G-F34BRDB91G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBVR5bgGq6LV-NPFc6rf1leaa4RnoVYXDo',
    appId: '1:885122827085:android:d7db55ac74c73e6b9e6d04',
    messagingSenderId: '885122827085',
    projectId: 'cardioresp-ai',
    storageBucket: 'cardioresp-ai.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBH_HfjBF1GJNGLrH6auGY2zqK3wSDFnO0',
    appId: '1:885122827085:ios:3fc6da579ae0bf329e6d04',
    messagingSenderId: '885122827085',
    projectId: 'cardioresp-ai',
    storageBucket: 'cardioresp-ai.appspot.com',
    iosBundleId: 'com.spsh.cardiofitai',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBH_HfjBF1GJNGLrH6auGY2zqK3wSDFnO0',
    appId: '1:885122827085:ios:3fc6da579ae0bf329e6d04',
    messagingSenderId: '885122827085',
    projectId: 'cardioresp-ai',
    storageBucket: 'cardioresp-ai.appspot.com',
    iosBundleId: 'com.spsh.cardiofitai',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDIy_QqInrk2yp3E3Jlua7e9icTBtWuzD8',
    appId: '1:885122827085:web:7316a3560291e78c9e6d04',
    messagingSenderId: '885122827085',
    projectId: 'cardioresp-ai',
    authDomain: 'cardioresp-ai.firebaseapp.com',
    storageBucket: 'cardioresp-ai.appspot.com',
    measurementId: 'G-PWMRSYLBJR',
  );
}
